
@startuml StoryboardController
scale 1.5
start

:进入分镜编辑页面;
:读取所有分镜表;
switch(点击按钮)
case(创建分镜表)
    :弹出对话框;
    if(是否填写数据合法) then(yes)
        :在数据库中创建;
        :刷新所有分镜表;
    else(no)
    endif
case(修改分镜表)
    :弹出对话框;
    if(是否填写数据合法) then(yes)
        :在数据库中修改;
        :刷新所有分镜表;
    else(no)
    endif
case(删除分镜表)
    if(是否有当前编辑分镜表) then(yes)
        :在数据库中删除;
        :刷新所有分镜表;
    else(no)
    endif
case(选择分镜表)
if(选择了与当前不同的分镜表或当前分镜表为null) then(yes)
    :将当前编辑分镜表设为所选分镜表;
else(no)
    :将当前编辑分镜表设为null;
endif
endswitch


stop
@enduml