@startuml HomePageState
scale 500 width

[*] --> ProjectUninitialized
ProjectUninitialized --> RetrievingProject: InitializeApp
RetrievingProject --> NoProjectRetrieved
RetrievingProject --> ProjectRetrieved
NoProjectRetrieved --> CreatingProject: CreateProject
ProjectRetrieved --> CreatingProject: CreateProject
ProjectRetrieved --> RetrievingProject: DeleteProject
CreatingProject --> RetrievingProject: SubmitCreateProject
ProjectRetrieved --> [*]

@enduml