@startuml SongInfoPageState
scale 500 width

[*] --> LyricUninitialized
LyricUninitialized --> RetrievingLyric : StartRetrieving
RetrievingLyric --> LyricRetrieved
LyricRetrieved --> RetrievingLyric : ChangeLyricData
LyricRetrieved --> RetrievingLyric : ImportLyric
LyricRetrieved --> RetrievingLyric : PressDelete
LyricRetrieved --> [*]

@enduml