
@startuml DataMigrationController
scale 1.5
start

:进入数据迁移页面;
switch(点击按钮)
case(导入Markdown)
    :弹出对话框;
    if(询问用户是否确认) then(yes)
        :从文件导入;
    else(no)
    endif
case(导入JSON)
    :弹出对话框;
    if(询问用户是否确认) then(yes)
        :从文件导入;
    else(no)
    endif
case(导出Markdown)
    :弹出对话框;
    if(询问用户是否确认) then(yes)
        :导出到文件;
    else(no)
    endif
case(导出JSON)
:弹出对话框;
if(询问用户是否确认) then(yes)
    :导出到文件;
else(no)
endif
endswitch


stop
@enduml