
@startuml FormationController
scale 1.5
start

:进入队形编辑页面;
:读取所有队形;
switch(点击按钮)
case(创建队形)
    :弹出对话框;
    if(是否填写数据合法) then(yes)
        :在数据库中创建;
        :刷新所有队形;
    else(no)
    endif
case(修改队形)
    :弹出对话框;
    if(是否填写数据合法) then(yes)
        :在数据库中修改;
        :刷新所有队形;
    else(no)
    endif
case(删除队形)
    if(是否有当前编辑队形) then(yes)
        :在数据库中删除;
        :刷新所有队形;
    else(no)
    endif
case(选择队形)
if(选择了与当前不同的队形或当前队形为null) then(yes)
    :将当前编辑队形设为所选队形;
else(no)
    :将当前编辑队形设为null;
endif
endswitch


stop
@enduml