
@startuml ProjectController
scale 1.5
start

:进入项目管理页面;
:读取所有项目;
switch(点击按钮)
case(创建项目)
    :弹出对话框;
    if(是否填写数据合法) then(yes)
        :在数据库中创建;
        :刷新所有项目;
    else(no)
    endif
case(修改项目)
    :弹出对话框;
    if(是否填写数据合法) then(yes)
        :在数据库中修改;
        :刷新所有项目;
    else(no)
    endif
case(删除项目)
    if(是否有当前编辑项目) then(yes)
        :在数据库中删除;
        :刷新所有项目;
    else(no)
    endif
case(选择项目)
if(选择了与当前不同的项目或当前项目为null) then(yes)
    :将当前编辑项目设为所选项目;
else(no)
    :将当前编辑项目设为null;
endif
endswitch


stop
@enduml