@startuml 用户与移动设备交互用例图
scale 1.5
'scale 1.5 | scale 200 width | scale 100 height | scale [max] 200x100

普通用户 <|-- 管理员
普通用户 <|-- 导演
普通用户 <|-- 分镜师
普通用户 <|-- 编舞师

普通用户 -> (登录)
普通用户 -> (注册)
(注册) -> (登录)
(登录) -up-> (修改个人信息)
(登录) --> (查看歌曲)
(登录) --> (迁移数据)
导演 --> (编辑项目)
(编辑项目) --> (分发分镜)
(编辑项目) --> (分发队形)
分镜师 --> (编辑分镜)
编舞师 --> (编辑队形)

管理员 --> (编辑歌曲)
管理员 --> (管理用户)

@enduml