@startuml Class

SNProject "1..*" -- "1" SNSong
SNProject "1..*" -- "1" SNShotTable
SNProject "1..*" -- "1" SNFormationTable
SNSong "1" -- "1..*" SNShotTable
SNSong "1" -- "1..*" SNFormationTable
SNSong "1" *-- "1..*" SNLyric
SNShotTable "1" *-- "1..*" SNShot
SNFormationTable "1" *-- "1..*" SNFormation


class SNProject {
    String id
    String dancerName
    DateTime createdTime
    DateTime modifiedTime
    String songId
    String shotTableId
    String formationTableId
    fromMap()
    toMap()
}

class SNSong {
    String id
    String name
    String coverId
    int lyricOffset
    String subordinateKikaku
    fromMap()
    toMap()
}

class SNLyric {
    String id
    Duration startTime
    Duration endTime
    String text
    String songId
    List<SNCharacter> soloPart
    fromMap()
    toMap()
}


class SNShotTable {
  String id
  String name
  String authorId
  String songId
  fromMap()
  toMap()
}


class SNShot {
    String id
    int sceneNumber
    int shotNumber
    Duration startTime
    Duration endTime
    String lyric
    String shotType
    String shotMovement
    String shotAngle
    String text
    String image
    String comment
    String tableId
    List<SNCharacter> characters
    fromMap()
    toMap()
}
class SNFormationTable {
  String id
  String name
  String authorId
  String songId

  fromMap()
  toMap()
}

class SNFormation {
    String id
    Duration startTime
    double posX
    double posY
    int curveX1X
    int curveX1Y
    int curveX2X
    int curveX2Y
    int curveY1X
    int curveY1Y
    int curveY2X
    int curveY2Y
    String characterName
    String tableId
    fromMap()
    toMap()
}

@enduml