@startuml HomePageState
scale 500 width

[*] --> ProjectUninitialized
ProjectUninitialized-->RetrievingProject:InitializeApp
RetrievingProject-->NoProjectRetrieved
RetrievingProject-->ProjectRetrieved
NoProjectRetrieved-->CreatingProject:AddProject
ProjectRetrieved-->CreatingProject:AddProject
ProjectRetrieved-->RetrievingProject:DeleteProject
CreatingProject-->RetrievingProject:ConfirmAddProject
ProjectRetrieved-->ProjectSelected:SelectAProject
ProjectSelected-->[*]
@enduml