@startuml ShotEditorPageState
scale 500 width

[*] --> ShotUninitialized
ShotUninitialized-->RetrievingShot:StartRetrieving
RetrievingShot-->ShotRetrieved
ShotRetrieved-->RetrievingShot:PressDelete
ShotRetrieved-->RetrievingShot:PressDeleteSelected
ShotRetrieved-->RetrievingShot:ChangeShotData
ShotRetrieved-->[*]

@enduml