@startuml 用户与移动设备交互用例图

User -> (登录)
User -> (注册)
(注册) -> (登录)
(登录) -> (编辑Project)
(登录) -up-> (修改个人信息)
(编辑Project) -> (选择Project)
(编辑Project) -up-> (创建Project)
(编辑Project) -up-> (修改Project)
(编辑Project) -up-> (删除Project)
(选择Project) --> (编辑Shot)
(选择Project) --> (编辑Song)
(选择Project) --> (编辑Formation)
(选择Project) --> (数据迁移)
(数据迁移) --> (从JSON导入)
(数据迁移) --> (导出为Markdown)


@enduml