import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          'At: ': '时间： ',
          'All Song List': '所有歌曲列表',
          'Information about Kikakus': '角色信息',
          'Create or Update Project': '创建或编辑项目',
          'Create or Update Song': '创建或编辑歌曲',
          'Created time': '创建日期',
          'Current project:': '当前项目：',
          'Dancer name': '舞团名称',
          'Data Migration': '数据迁移',
          'Delete': '删除',
          'End time': '结束时间',
          'Formation': '队形',
          'Home Page': '首页',
          'Input project ID:': '您也可以自行输入项目ID：',
          'Lyric text': '歌词文本',
          'Or another project:': '或是选择另一项目：',
          'Song name': '歌曲名',
          'Song duration': '歌曲时长',
          'Song Information': '歌曲信息',
          'Song List': '歌曲列表',
          'Start time': '开始时间',
          'Storyboard': '分镜',
          'Submit': '完成',
          'Subordinates': '所属企划',
          'User Information': '用户信息',
          'Welcome back!': '欢迎回来！',
          'With: ': '对象： ',
        },
        'ja_CN': {
          'At: ': '日時： ',
          'All Song List': '全ての曲',
          'Information about Kikakus': 'キャラクターの情報',
          'Create or Update Project': 'プロジェクトを作成/編集',
          'Create or Update Song': '曲を作成/編集',
          'Created time': '作成日時',
          'Current project:': '現在のプロジェクト：',
          'Dancer name': 'ダンサーの名前',
          'Data Migration': 'データ移行',
          'Delete': '削除',
          'End time': '終了時刻',
          'Formation': 'フォーメーション',
          'Home Page': 'ホームページ',
          'Input project ID:': 'プロジェクトの番号を入力：',
          'Lyric text': '歌詞',
          'Or another project:': 'ほかのプロジェクト：',
          'Song name': '曲名',
          'Song Information': '曲の情報',
          'Song List': '曲のリスト',
          'Song duration': '曲の長さ',
          'Start time': '開始時刻',
          'Storyboard': 'ストーリーボード',
          'Submit': '完了',
          'Subordinates': '所属の企画',
          'User Information': 'ユーザーの情報',
          'Welcome back!': 'お帰りなさい♪',
          'With: ': '相手： ',
        }
      };
}
